### ISSUE TITLE
安装的时候程序就崩溃了

### ISSUE THREAD

**Issue by meiqi1992** [wJianZhong/react-native-easy-downloader#2]
下载成功了，但是安装的时候崩溃了

**Comment by meiqi1992** [comment]
下载路径下的.apk文件 打不开

**Comment by thiszhong** [comment]
@meiqi1992 
`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>`
权限有吗？
机型和系统版本提供下，有测试example下的例子吗？

**Comment by thiszhong** [comment]
可能你的apk文件或链接有些问题

**Comment by thiszhong** [comment]
可以试下 v0.1.0
